const constants = {
   FETCH_QUIZES_START: "FETCH_QUIZES_START",
   FETCH_QUIZES_SUCCESS: "FETCH_QUIZES_SUCCESS",
   FETCH_QUIZES_ERROR: "FETCH_QUIZES_ERROR",
   FETCH_QUIZ_SUCCESS: "FETCH_QUIZ_SUCCESS",

   FINISH_QUIZ: "FINISH_QUIZ",
   QUIZ_NEXT_QUESTION: "QUIZ_NEXT_QUESTION",
   QUIZ_RETRY: "QUIZ_RETRY",
   QUIZ_SET_STATE: "QUIZ_SET_STATE",

   CREATE_QUIZ_QUESTION:"CREATE_QUIZ_QUESTION",
   RESET_QUIZ_CREATION:"RESET_QUIZ_CREATION",

   REGISTER_SUCCESS: 'REGISTER_SUCCESS',
   REGISTER_FAIL: 'REGISTER_FAIL',

   USER_LOADED: 'USER_LOADED',
   AUTH_ERROR: 'AUTH_ERROR',

   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
   LOGIN_FAIL: 'LOGIN_FAIL',

   LOGOUT: 'LOGOUT'
};

export default constants;